import { test, expect } from '../fixtures/browser-test';

test('B01 anonymous login uses actual clients before owner reads', async ({ page, api }) => {
  await page.goto('/');
  await expect(page.getByLabel('手机号', { exact: true })).toBeVisible();
  await page.getByLabel('手机号', { exact: true }).fill('13800138000');
  await page.getByRole('button', { name: '获取验证码', exact: true }).click();
  await expect(page.getByText('验证码已发送', { exact: true })).toBeVisible();
  await page.getByLabel('验证码', { exact: true }).fill('123456');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('textbox', { name: '统一输入', exact: true })).toBeVisible();
  expect(api.count('POST', '/api/auth/otp/start')).toBe(1);
  expect(api.count('POST', '/api/auth/otp/verify')).toBe(1);
  expect(api.identity).toBe('A');
  const input = page.getByRole('textbox', { name: '统一输入', exact: true });
  const originalUrl = page.url();
  await input.fill('A的未提交旅行草稿');
  await page.getByRole('button', { name: '菜单', exact: true }).click();
  await expect(page.getByRole('heading', { name: '设置', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '退出当前登录', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: '退出当前登录', exact: true });
  await expect(confirmation).toBeVisible();
  await confirmation.getByRole('button', { name: '取消', exact: true }).click();
  await expect(confirmation).toHaveCount(0);
  await page.getByRole('button', { name: '返回首页', exact: true }).click();
  await expect(input).toHaveValue('A的未提交旅行草稿');
  expect(page.url()).toBe(originalUrl);
  expect(api.count('POST', '/api/logout')).toBe(0);
  expect(api.count('POST', '/api/home/input/parse')).toBe(0);
  expect(api.count('POST', '/api/ingest/xhs')).toBe(0);
});
