/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ingest/start": {
    /**
     * Start ingest of a single Xiaohongshu link (async)
     * @deprecated
     * @description Use POST /ingest/xhs instead.
     */
    post: operations["startIngest"];
  };
  "/ingest/xhs": {
    /** Start ingest by Xiaohongshu share link (async) */
    post: operations["ingestXhs"];
  };
  "/ingest/{job_id}/events": {
    /** SSE stream for ingest job events (alias path) */
    get: operations["ingestEvents"];
  };
  "/sse/ingest/{ingest_id}": {
    /**
     * SSE stream for ingest job events
     * @deprecated
     * @description Use GET /ingest/{job_id}/events instead.
     */
    get: operations["sseIngest"];
  };
  "/plan/generate": {
    /** Generate day-level skeleton (partial fill) asynchronously */
    post: operations["planGenerate"];
  };
  "/sse/plan/{plan_job_id}": {
    /** SSE stream for plan generation events */
    get: operations["ssePlan"];
  };
  "/plan/slots/{slot_id}": {
    /** Edit a slot (move/retime/replace/delete) with optimistic locking */
    patch: operations["editSlot"];
  };
  "/plan/ai-fill": {
    /**
     * Start one-shot AI fill over remaining controllable slots (async)
     * @deprecated
     * @description Use POST /fill/apply instead.
     */
    post: operations["aiFill"];
  };
  "/fill/apply": {
    /** Apply AI fill over remaining controllable slots (async) */
    post: operations["fillApply"];
  };
  "/plan/{plan_id}/result-sheet": {
    /** Get read-only result sheet (slots + AI suggestions + citations) */
    get: operations["getResultSheet"];
  };
  "/plan/{plan_id}": {
    /** Get plan (alias of result-sheet for convenience) */
    get: operations["getPlan"];
  };
  "/plan/slots/{slot_id}/status": {
    /** Toggle or set slot status (checked) */
    patch: operations["patchSlotStatus"];
  };
  "/plan/slots/{slot_id}/overrides": {
    /** Clear slot text overrides (revert to AI) */
    delete: operations["deleteSlotOverrides"];
    /** Set or update slot text overrides (do/prepare/notice) */
    patch: operations["patchSlotOverrides"];
  };
  "/sse/fill/{fill_run_id}": {
    /** SSE stream for AI fill run */
    get: operations["sseFill"];
  };
  "/export/png": {
    /** Export itinerary as PNG/WebP, auto-slicing by day when needed */
    post: operations["exportPng"];
  };
  "/plan/validate": {
    /** Validate plan feasibility and return conflicts/suggestions */
    post: operations["planValidate"];
  };
  "/plan/fix": {
    /** Apply a suggested fix or atomic ops to reduce conflicts */
    post: operations["planFix"];
  };
  "/plan/hq/start": {
    /** Start high-quality background planning for a plan */
    post: operations["hqStart"];
  };
  "/plan/hq/status": {
    /** Get HQ job status */
    get: operations["hqStatus"];
  };
  "/plan/hq/adopt": {
    /** Adopt the HQ plan result and merge as current plan */
    post: operations["hqAdopt"];
  };
  "/byok/validate": {
    /** Validate a user-provided API key without storing it */
    post: operations["byokValidate"];
  };
  "/byok/save": {
    /** Save BYOK (encrypted) — alias for /user-key */
    post: operations["byokSave"];
  };
  "/search/poi": {
    /** Text-only POI search (MVP FR44-lite) */
    get: operations["searchPoi"];
  };
  "/plans/{plan_id}/candidates": {
    /** Manually add a candidate by name/address/coords (MVP minimal) */
    post: operations["addCandidate"];
  };
  "/plan/days/{day}/hotel": {
    /** Set or change hotel for a day (display-only slot) */
    patch: operations["setHotel"];
  };
  "/auth/otp/start": {
    /** Start OTP flow (SMS) */
    post: operations["authOtpStart"];
  };
  "/auth/otp/verify": {
    /** Verify OTP and create session */
    post: operations["authOtpVerify"];
  };
  "/sessions/me": {
    /** Get current session */
    get: operations["sessionsMe"];
  };
  "/sessions": {
    /** List my sessions */
    get: operations["sessionsList"];
  };
  "/sessions/{id}": {
    /** Revoke a session */
    delete: operations["sessionsDelete"];
  };
  "/feedback/link": {
    /**
     * Get feedback product URL (support.qq.com)
     * @description Returns the official product URL (https://support.qq.com/product/{PRODUCT_ID}). If product login state is enabled server-side, parameters per official spec may be attached.
     */
    get: operations["getFeedbackLink"];
  };
  "/auth/bind/apple": {
    /** Bind Apple identity */
    post: operations["bindApple"];
  };
  "/auth/bind/wechat": {
    /** Bind WeChat identity */
    post: operations["bindWeChat"];
  };
  "/user-key": {
    /** Get masked BYOK status */
    get: operations["getUserKey"];
    /** Set or replace BYOK (encrypted and envelope stored) */
    post: operations["setUserKey"];
    /** Delete BYOK */
    delete: operations["deleteUserKey"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    FeedbackLinkResponse: {
      /** Format: uri */
      url: string;
    };
    Session: {
      id: string;
      device_id: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: date-time */
      created_at?: string;
    };
    SessionResponse: {
      user?: {
        id?: string;
        phone?: string | null;
      };
      session?: components["schemas"]["Session"];
    };
    ErrorEnvelope: {
      /** @example INGEST_TIMEOUT */
      error_code: string;
      error_message: string;
      retriable?: boolean;
      details?: {
        [key: string]: unknown;
      };
    };
    IngestStartRequest: {
      /** @enum {string} */
      source: "xhs";
      share_text?: string | null;
      /** Format: uri */
      url?: string | null;
      /** @description Bypass idempotency (admin/feature-flag) */
      force?: boolean;
    };
    IngestStartResponse: {
      ingest_id: string;
      /** @enum {string} */
      state: "created";
      /** @example /sse/ingest/ing_123 */
      sse_url?: string;
    };
    IngestXhsRequest: {
      /** Format: uri */
      url: string;
    };
    PlanGenerateRequest: {
      city: string;
      /** Format: date */
      start_date: string;
      days: number;
      /**
       * @default normal
       * @enum {string}
       */
      pace?: "slow" | "normal" | "fast";
      selected_items?: ({
          item_id: string;
          poi_id?: string;
          must_go?: boolean;
          /** @enum {string|null} */
          time_hint?: "morning" | "afternoon" | "evening" | null;
          stay_minutes_hint?: number;
        })[];
    };
    PlanGenerateResponse: {
      plan_id: string;
      plan_job_id: string;
      /** @example /sse/plan/pj_1 */
      sse_url?: string;
    };
    SlotPatchRequest: {
      /** @enum {string} */
      op: "move" | "retime" | "replace" | "delete";
      new_day?: number;
      new_start?: string;
      new_end?: string;
      replace_with_poi_id?: string;
    };
    SlotPatchResponse: {
      undo_token: string;
      plan_rev: number;
    };
    AiFillRequest: {
      plan_id: string;
      /** @default false */
      dry_run?: boolean;
    };
    AiFillResponse: {
      fill_run_id: string;
      /** @example /sse/fill/fr_1 */
      sse_url?: string;
    };
    ExportPngRequest: {
      plan_id: string;
      /**
       * @default 1080
       * @enum {integer}
       */
      width_px?: 1080 | 1242;
      /** @default true */
      slice_by_day?: boolean;
      /**
       * @default light
       * @enum {string}
       */
      theme?: "light" | "dark";
    };
    ExportPngResponse: {
      files: ({
          day?: number | null;
          /** Format: uri */
          url: string;
        })[];
      /** @enum {string} */
      format?: "webp" | "jpeg";
      fallback_reason?: string | null;
    };
    SlotRecommendation: {
      do?: string | null;
      prepare?: string | null;
      notice?: string | null;
      /**
       * @default ai
       * @enum {string}
       */
      source?: "ai" | "override";
    };
    ResultSheetResponse: {
      plan_id: string;
      days: ({
          day: number;
          hotel?: ({
            name?: string;
            address?: string;
            map_url?: string | null;
          }) | null;
          slots: ({
              slot_id: string;
              /** @enum {string} */
              type: "activity" | "dining" | "nightlife" | "transport" | "hotel";
              start: string;
              end: string;
              title: string;
              checked?: boolean;
              why_short?: string | null;
              citations?: string[] | null;
              recommendation?: components["schemas"]["SlotRecommendation"];
            })[];
        })[];
    };
    SlotStatusPatchRequest: {
      checked?: boolean;
    };
    SlotStatusPatchResponse: {
      slot_id: string;
      checked: boolean;
    };
    SlotOverridesPatchRequest: {
      /** @description Plain text only; no markup/HTML */
      do?: string | null;
      /** @description Plain text only; no markup/HTML */
      prepare?: string | null;
      /** @description Plain text only; no markup/HTML */
      notice?: string | null;
    };
    SlotOverridesPatchResponse: {
      slot_id: string;
      recommendation?: components["schemas"]["SlotRecommendation"];
    };
    SearchPoiItem: {
      poi_id: string;
      name: string;
      address: string;
      distance_m?: number | null;
    };
    CandidateAddRequest: {
      name: string;
      address?: string | null;
      /** Format: double */
      lat?: number | null;
      /** Format: double */
      lng?: number | null;
    };
    CandidateAddResponse: {
      candidate_id: string;
    };
    SetHotelRequest: {
      plan_id: string;
      hotel_poi_id: string;
    };
    /**
     * @description Feasibility conflict type detected by Validator
     * @enum {string}
     */
    ValidatorConflictType: "no_coords" | "closed" | "cross_day_unreachable" | "too_far" | "overtime" | "open_gap_short" | "transport_boundary" | "hotel_boundary";
    /** @enum {string} */
    ConflictSeverity: "hard" | "soft";
    /**
     * @description A single conflict with optional fix suggestions
     * @example {
     *   "type": "too_far",
     *   "severity": "soft",
     *   "day": 2,
     *   "slot_id": "s_abc",
     *   "details": {
     *     "commute_minutes": 28,
     *     "limit_minutes": 18
     *   },
     *   "suggestions": [
     *     {
     *       "id": "fix_1",
     *       "conflict_type": "too_far",
     *       "safe": true,
     *       "requires_user_input": false,
     *       "score": 0.87,
     *       "actions": [
     *         {
     *           "type": "reorder",
     *           "notes": "Swap with previous slot to reduce commute"
     *         }
     *       ],
     *       "apply_sequence": [
     *         {
     *           "op": "move",
     *           "slot_id": "s_abc",
     *           "new_day": 2,
     *           "new_start": "14:00",
     *           "new_end": "16:00"
     *         },
     *         {
     *           "op": "move",
     *           "slot_id": "s_prev",
     *           "new_day": 2,
     *           "new_start": "16:00",
     *           "new_end": "18:00"
     *         }
     *       ]
     *     },
     *     {
     *       "id": "fix_2",
     *       "conflict_type": "too_far",
     *       "safe": true,
     *       "requires_user_input": true,
     *       "score": 0.81,
     *       "actions": [
     *         {
     *           "type": "replace_with_alternative",
     *           "notes": "Use nearer candidate"
     *         }
     *       ],
     *       "apply_sequence": [
     *         {
     *           "op": "replace",
     *           "slot_id": "s_abc",
     *           "replace_with_poi_id": "poi_nearby_1"
     *         }
     *       ]
     *     }
     *   ]
     * }
     */
    ValidatorConflict: {
      type: components["schemas"]["ValidatorConflictType"];
      severity: components["schemas"]["ConflictSeverity"];
      day?: number | null;
      slot_id?: string | null;
      details?: {
        [key: string]: unknown;
      };
      suggestions?: components["schemas"]["FixSuggestion"][];
    };
    /**
     * @description High-level fix strategy
     * @enum {string}
     */
    FixActionType: "reorder" | "move" | "retime" | "shorten_stay" | "replace_with_alternative" | "shift_day" | "align_to_boundary" | "suggest_insert_candidate";
    FixAction: {
      type: components["schemas"]["FixActionType"];
      notes?: string | null;
    };
    /**
     * @description Atomic operations map to existing APIs:
     * - move/retime/replace/delete → PATCH /plan/slots/{slot_id}
     * - set_hotel → PATCH /plan/days/{day}/hotel
     */
    FixAtomicOperation: {
      /** @enum {string} */
      op: "move" | "retime" | "replace" | "delete" | "set_hotel";
      slot_id?: string | null;
      day?: number | null;
      new_day?: number | null;
      new_start?: string | null;
      new_end?: string | null;
      replace_with_poi_id?: string | null;
      hotel_poi_id?: string | null;
    };
    /**
     * @example {
     *   "id": "fix_1",
     *   "conflict_type": "too_far",
     *   "safe": true,
     *   "requires_user_input": false,
     *   "score": 0.87,
     *   "actions": [
     *     {
     *       "type": "reorder",
     *       "notes": "Swap with previous slot to reduce commute"
     *     }
     *   ],
     *   "apply_sequence": [
     *     {
     *       "op": "move",
     *       "slot_id": "s_abc",
     *       "new_day": 2,
     *       "new_start": "14:00",
     *       "new_end": "16:00"
     *     }
     *   ]
     * }
     */
    FixSuggestion: {
      id: string;
      conflict_type: components["schemas"]["ValidatorConflictType"];
      /** @description Does not modify frozen/must_go/time_hint */
      safe?: boolean;
      /** @description Needs user to pick an alternative or candidate */
      requires_user_input?: boolean;
      /**
       * Format: double
       * @description Higher is better; deterministic tie-break
       */
      score?: number;
      actions: components["schemas"]["FixAction"][];
      /** @description Ordered atomic ops to apply using existing endpoints */
      apply_sequence?: components["schemas"]["FixAtomicOperation"][];
    };
  };
  responses: {
    /** @description Bad Request */
    Error400: {
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Unauthorized */
    Error401: {
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Conflict (Optimistic locking / idempotency) */
    Error409: {
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Too Many Requests (rate limited) */
    Error429: {
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Internal Server Error */
    Error500: {
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Start ingest of a single Xiaohongshu link (async)
   * @deprecated
   * @description Use POST /ingest/xhs instead.
   */
  startIngest: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngestStartRequest"];
      };
    };
    responses: {
      /** @description Accepted; ingest job created */
      202: {
        headers: {
          /** @description Correlation id for tracing */
          "X-Trace-Id"?: string;
        };
        content: {
          "application/json": components["schemas"]["IngestStartResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** Start ingest by Xiaohongshu share link (async) */
  ingestXhs: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngestXhsRequest"];
      };
    };
    responses: {
      /** @description Accepted; ingest job created */
      202: {
        content: {
          "application/json": components["schemas"]["IngestStartResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** SSE stream for ingest job events (alias path) */
  ingestEvents: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Server-Sent Events stream */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /**
   * SSE stream for ingest job events
   * @deprecated
   * @description Use GET /ingest/{job_id}/events instead.
   */
  sseIngest: {
    parameters: {
      path: {
        ingest_id: string;
      };
    };
    responses: {
      /** @description Server-Sent Events stream */
      200: {
        headers: {
          "Cache-Control"?: string;
          "X-Trace-Id"?: string;
        };
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Generate day-level skeleton (partial fill) asynchronously */
  planGenerate: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanGenerateRequest"];
      };
    };
    responses: {
      /** @description Accepted; plan job created */
      202: {
        headers: {
          "X-Trace-Id"?: string;
        };
        content: {
          "application/json": components["schemas"]["PlanGenerateResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      409: components["responses"]["Error409"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** SSE stream for plan generation events */
  ssePlan: {
    parameters: {
      path: {
        plan_job_id: string;
      };
    };
    responses: {
      /** @description Server-Sent Events stream for plan phases */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Edit a slot (move/retime/replace/delete) with optimistic locking */
  editSlot: {
    parameters: {
      header: {
        /** @description Current plan revision for optimistic concurrency */
        "If-Match-Rev": number;
      };
      path: {
        slot_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SlotPatchRequest"];
      };
    };
    responses: {
      /** @description Slot edited */
      200: {
        content: {
          "application/json": components["schemas"]["SlotPatchResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      409: components["responses"]["Error409"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /**
   * Start one-shot AI fill over remaining controllable slots (async)
   * @deprecated
   * @description Use POST /fill/apply instead.
   */
  aiFill: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiFillRequest"];
      };
    };
    responses: {
      /** @description Accepted; fill run created */
      202: {
        content: {
          "application/json": components["schemas"]["AiFillResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** Apply AI fill over remaining controllable slots (async) */
  fillApply: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiFillRequest"];
      };
    };
    responses: {
      /** @description Accepted; fill run created */
      202: {
        content: {
          "application/json": components["schemas"]["AiFillResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** Get read-only result sheet (slots + AI suggestions + citations) */
  getResultSheet: {
    parameters: {
      path: {
        plan_id: string;
      };
    };
    responses: {
      /** @description Result sheet */
      200: {
        content: {
          "application/json": components["schemas"]["ResultSheetResponse"];
        };
      };
      401: components["responses"]["Error401"];
      404: components["responses"]["Error400"];
    };
  };
  /** Get plan (alias of result-sheet for convenience) */
  getPlan: {
    parameters: {
      path: {
        plan_id: string;
      };
    };
    responses: {
      /** @description Plan (result-sheet payload) */
      200: {
        content: {
          "application/json": components["schemas"]["ResultSheetResponse"];
        };
      };
      401: components["responses"]["Error401"];
      404: components["responses"]["Error400"];
    };
  };
  /** Toggle or set slot status (checked) */
  patchSlotStatus: {
    parameters: {
      path: {
        slot_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SlotStatusPatchRequest"];
      };
    };
    responses: {
      /** @description Status updated */
      200: {
        content: {
          "application/json": components["schemas"]["SlotStatusPatchResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Clear slot text overrides (revert to AI) */
  deleteSlotOverrides: {
    parameters: {
      path: {
        slot_id: string;
      };
    };
    responses: {
      /** @description Cleared */
      204: {
        content: never;
      };
      401: components["responses"]["Error401"];
    };
  };
  /** Set or update slot text overrides (do/prepare/notice) */
  patchSlotOverrides: {
    parameters: {
      path: {
        slot_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SlotOverridesPatchRequest"];
      };
    };
    responses: {
      /** @description Overrides updated */
      200: {
        content: {
          "application/json": components["schemas"]["SlotOverridesPatchResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** SSE stream for AI fill run */
  sseFill: {
    parameters: {
      path: {
        fill_run_id: string;
      };
    };
    responses: {
      /** @description Server-Sent Events stream for fill phases and result updates */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Export itinerary as PNG/WebP, auto-slicing by day when needed */
  exportPng: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportPngRequest"];
      };
    };
    responses: {
      /** @description Exported files */
      200: {
        content: {
          "application/json": components["schemas"]["ExportPngResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** Validate plan feasibility and return conflicts/suggestions */
  planValidate: {
    requestBody: {
      content: {
        "application/json": {
          plan_id: string;
        };
      };
    };
    responses: {
      /** @description Validation results */
      200: {
        content: {
          "application/json": {
            hard_cnt?: number;
            soft_cnt?: number;
            conflicts?: components["schemas"]["ValidatorConflict"][];
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Apply a suggested fix or atomic ops to reduce conflicts */
  planFix: {
    requestBody: {
      content: {
        "application/json": {
          plan_id: string;
          suggestion_id?: string | null;
          apply_sequence?: components["schemas"]["FixAtomicOperation"][];
        };
      };
    };
    responses: {
      /** @description Fix applied */
      200: {
        content: never;
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      409: components["responses"]["Error409"];
    };
  };
  /** Start high-quality background planning for a plan */
  hqStart: {
    requestBody: {
      content: {
        "application/json": {
          plan_id: string;
        };
      };
    };
    responses: {
      /** @description HQ job started */
      202: {
        content: {
          "application/json": {
            hq_job_id?: string;
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Get HQ job status */
  hqStatus: {
    parameters: {
      query: {
        hq_job_id: string;
      };
    };
    responses: {
      /** @description HQ status */
      200: {
        content: {
          "application/json": {
            /** @enum {string} */
            state?: "running" | "done" | "failed";
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Adopt the HQ plan result and merge as current plan */
  hqAdopt: {
    requestBody: {
      content: {
        "application/json": {
          plan_id: string;
          hq_job_id: string;
        };
      };
    };
    responses: {
      /** @description Adopted */
      200: {
        content: never;
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Validate a user-provided API key without storing it */
  byokValidate: {
    requestBody: {
      content: {
        "application/json": {
          key: string;
        };
      };
    };
    responses: {
      /** @description Validation result */
      200: {
        content: {
          "application/json": {
            valid?: boolean;
            provider?: string | null;
          };
        };
      };
      400: components["responses"]["Error400"];
    };
  };
  /** Save BYOK (encrypted) — alias for /user-key */
  byokSave: {
    requestBody: {
      content: {
        "application/json": {
          key: string;
        };
      };
    };
    responses: {
      /** @description Saved */
      204: {
        content: never;
      };
      400: components["responses"]["Error400"];
    };
  };
  /** Text-only POI search (MVP FR44-lite) */
  searchPoi: {
    parameters: {
      query: {
        city: string;
        q: string;
        topk?: number;
      };
    };
    responses: {
      /** @description Top‑K results */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["SearchPoiItem"][];
          };
        };
      };
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** Manually add a candidate by name/address/coords (MVP minimal) */
  addCandidate: {
    parameters: {
      path: {
        plan_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CandidateAddRequest"];
      };
    };
    responses: {
      /** @description Added candidate */
      200: {
        content: {
          "application/json": components["schemas"]["CandidateAddResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Set or change hotel for a day (display-only slot) */
  setHotel: {
    parameters: {
      path: {
        day: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetHotelRequest"];
      };
    };
    responses: {
      /** @description Hotel updated */
      200: {
        content: never;
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
    };
  };
  /** Start OTP flow (SMS) */
  authOtpStart: {
    requestBody: {
      content: {
        "application/json": {
          phone: string;
          captcha_token?: string | null;
        };
      };
    };
    responses: {
      /** @description OTP sent (or simulated for test) */
      200: {
        content: {
          "application/json": {
            /** @enum {string} */
            status?: "ok";
          };
        };
      };
      400: components["responses"]["Error400"];
      429: components["responses"]["Error429"];
    };
  };
  /** Verify OTP and create session */
  authOtpVerify: {
    requestBody: {
      content: {
        "application/json": {
          phone: string;
          code: string;
          device_id?: string;
        };
      };
    };
    responses: {
      /** @description Session created */
      200: {
        headers: {
          "X-Device-Id"?: string;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
    };
  };
  /** Get current session */
  sessionsMe: {
    responses: {
      /** @description Current session */
      200: {
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      401: components["responses"]["Error401"];
    };
  };
  /** List my sessions */
  sessionsList: {
    responses: {
      /** @description Sessions */
      200: {
        content: {
          "application/json": {
            sessions?: components["schemas"]["Session"][];
          };
        };
      };
      401: components["responses"]["Error401"];
    };
  };
  /** Revoke a session */
  sessionsDelete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
      401: components["responses"]["Error401"];
    };
  };
  /**
   * Get feedback product URL (support.qq.com)
   * @description Returns the official product URL (https://support.qq.com/product/{PRODUCT_ID}). If product login state is enabled server-side, parameters per official spec may be attached.
   */
  getFeedbackLink: {
    parameters: {
      query?: {
        /** @description Source page or context for analytics. */
        source?: string;
      };
    };
    responses: {
      /** @description Product URL */
      200: {
        content: {
          "application/json": components["schemas"]["FeedbackLinkResponse"];
        };
      };
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
    };
  };
  /** Bind Apple identity */
  bindApple: {
    requestBody: {
      content: {
        "application/json": {
          id_token: string;
        };
      };
    };
    responses: {
      /** @description Bound */
      200: {
        content: never;
      };
      401: components["responses"]["Error401"];
    };
  };
  /** Bind WeChat identity */
  bindWeChat: {
    requestBody: {
      content: {
        "application/json": {
          code: string;
        };
      };
    };
    responses: {
      /** @description Bound */
      200: {
        content: never;
      };
      401: components["responses"]["Error401"];
    };
  };
  /** Get masked BYOK status */
  getUserKey: {
    responses: {
      /** @description Key status */
      200: {
        content: {
          "application/json": {
            configured?: boolean;
          };
        };
      };
    };
  };
  /** Set or replace BYOK (encrypted and envelope stored) */
  setUserKey: {
    requestBody: {
      content: {
        "application/json": {
          key: string;
        };
      };
    };
    responses: {
      /** @description Saved */
      204: {
        content: never;
      };
      400: components["responses"]["Error400"];
    };
  };
  /** Delete BYOK */
  deleteUserKey: {
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
      401: components["responses"]["Error401"];
    };
  };
}
