export const BUILT_IN_POI_DATA_VERSION = 'xiamen-top50-2026-07-27-v1';

export const BUILT_IN_POI_NAMES: Readonly<Record<string, readonly string[]>> = {
  厦门: [
    '鼓浪屿',
    '日光岩',
    '菽庄花园',
    '皓月园',
    '厦门大学',
    '南普陀寺',
    '胡里山炮台',
    '环岛路',
    '曾厝垵',
    '中山路步行街',
    '沙坡尾',
    '厦门园林植物园',
    '钟鼓索道',
    '八市',
    '白城沙滩',
    '黄厝海滩',
    '演武大桥观景平台',
    '集美学村',
    '十里长堤',
    '园博苑',
    '海湾公园',
    '铁路文化公园',
    '猫街',
    '顶澳仔猫街',
    '五缘湾湿地公园',
    '五缘湾帆船港',
    '观音山梦幻海岸',
    '椰风寨',
    '音乐广场',
    '山海健康步道',
    '鸿山公园',
    '狐尾山公园',
    '筼筜湖',
    '海沧大桥旅游区',
    '天竺山森林公园',
    '同安影视城',
    '北辰山',
    '梵天寺',
    '大嶝小镇',
    '小嶝岛',
    '翔安香山',
    '鼓浪屿钢琴博物馆',
    '风琴博物馆',
    '龙头路',
    '最美转角',
    '郑成功纪念馆',
    '厦门科技馆',
    '厦门市博物馆',
    '华新路',
    '海上世界',
  ],
};

export function getBuiltInPoiManifest(city: string) {
  return (BUILT_IN_POI_NAMES[city] ?? []).map((name, rank) => ({
    dataVersion: BUILT_IN_POI_DATA_VERSION,
    rank,
    name,
  }));
}
